connectors:
- proxmox
pipelines:
- cron: 0 5 31 2 *
  name: Debug
  pipeline:
  - check_method: stdout_contains
    check_pattern: OK
    exec: test.sh
    exec_method: script
    id: test .sh script
    if_failed: null
    requires: []
  runner: proxmox_ct
